"""add community memberships

Revision ID: 00a44b575672
Revises: c43bf0ce045e
Create Date: 2026-06-24 21:13:04.672268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00a44b575672'
down_revision: Union[str, Sequence[str], None] = 'c43bf0ce045e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('community_memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('community_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_community_memberships_id'), 'community_memberships', ['id'], unique=False)
    op.add_column('communities', sa.Column('cadence', sa.String(), nullable=True))
    op.add_column('communities', sa.Column('activity', sa.String(), nullable=True))
    op.drop_column('communities', 'joined')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('communities', sa.Column('joined', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('communities', 'activity')
    op.drop_column('communities', 'cadence')
    op.drop_index(op.f('ix_community_memberships_id'), table_name='community_memberships')
    op.drop_table('community_memberships')
    # ### end Alembic commands ###
