"""add role based student and alumni profiles

Revision ID: 6a48ee39685b
Revises: bdad87a3b0a7
Create Date: 2026-06-29 22:27:39.986242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a48ee39685b'
down_revision: Union[str, Sequence[str], None] = 'bdad87a3b0a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


ALUMNI_USER_ID_UNIQUE_CONSTRAINT = 'uq_alumni_profiles_user_id'


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('roll_number', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('year_of_study', sa.Integer(), nullable=True),
    sa.Column('cgpa', sa.Float(), nullable=True),
    sa.Column('skills', sa.Text(), nullable=True),
    sa.Column('linkedin_url', sa.String(), nullable=True),
    sa.Column('github_url', sa.String(), nullable=True),
    sa.Column('career_goals', sa.Text(), nullable=True),
    sa.Column('verification_status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_student_profiles_id'), 'student_profiles', ['id'], unique=False)
    op.add_column('alumni_profiles', sa.Column('department', sa.String(), nullable=True))
    op.add_column('alumni_profiles', sa.Column('graduation_year', sa.Integer(), nullable=True))
    op.add_column('alumni_profiles', sa.Column('current_role', sa.String(), nullable=True))
    op.add_column('alumni_profiles', sa.Column('company', sa.String(), nullable=True))
    op.add_column('alumni_profiles', sa.Column('industry', sa.String(), nullable=True))
    op.add_column('alumni_profiles', sa.Column('experience_years', sa.Integer(), nullable=True))
    op.add_column('alumni_profiles', sa.Column('linkedin_url', sa.String(), nullable=True))
    op.add_column('alumni_profiles', sa.Column('mentorship_areas', sa.Text(), nullable=True))
    op.add_column('alumni_profiles', sa.Column('is_starred', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('alumni_profiles', sa.Column('rating', sa.Float(), nullable=False, server_default='0'))
    op.add_column('alumni_profiles', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')))
    op.alter_column('alumni_profiles', 'is_starred', server_default=None)
    op.alter_column('alumni_profiles', 'rating', server_default=None)
    op.alter_column('alumni_profiles', 'created_at', server_default=None)
    op.alter_column('alumni_profiles', 'focus',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('alumni_profiles', 'chapter',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('alumni_profiles', 'availability',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('alumni_profiles', 'response_time',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('alumni_profiles', 'current_project',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('alumni_profiles', 'impact',
               existing_type=sa.TEXT(),
               nullable=True)
    op.create_unique_constraint(ALUMNI_USER_ID_UNIQUE_CONSTRAINT, 'alumni_profiles', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(ALUMNI_USER_ID_UNIQUE_CONSTRAINT, 'alumni_profiles', type_='unique')
    op.alter_column('alumni_profiles', 'impact',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('alumni_profiles', 'current_project',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('alumni_profiles', 'response_time',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('alumni_profiles', 'availability',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('alumni_profiles', 'chapter',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('alumni_profiles', 'focus',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('alumni_profiles', 'created_at')
    op.drop_column('alumni_profiles', 'rating')
    op.drop_column('alumni_profiles', 'is_starred')
    op.drop_column('alumni_profiles', 'mentorship_areas')
    op.drop_column('alumni_profiles', 'linkedin_url')
    op.drop_column('alumni_profiles', 'experience_years')
    op.drop_column('alumni_profiles', 'industry')
    op.drop_column('alumni_profiles', 'company')
    op.drop_column('alumni_profiles', 'current_role')
    op.drop_column('alumni_profiles', 'graduation_year')
    op.drop_column('alumni_profiles', 'department')
    op.drop_index(op.f('ix_student_profiles_id'), table_name='student_profiles')
    op.drop_table('student_profiles')
    # ### end Alembic commands ###
