"""add mentorship requests and sessions

Revision ID: c859296e6aa6
Revises: c39e5ac7fef3
Create Date: 2026-06-30 21:29:16.819017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c859296e6aa6'
down_revision: Union[str, Sequence[str], None] = 'c39e5ac7fef3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mentorship_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('alumni_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['alumni_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mentorship_requests_id'), 'mentorship_requests', ['id'], unique=False)
    op.create_table('mentorship_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('alumni_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('meeting_link', sa.String(), nullable=True),
    sa.Column('recording_url', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['alumni_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['mentorship_requests.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mentorship_sessions_id'), 'mentorship_sessions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mentorship_sessions_id'), table_name='mentorship_sessions')
    op.drop_table('mentorship_sessions')
    op.drop_index(op.f('ix_mentorship_requests_id'), table_name='mentorship_requests')
    op.drop_table('mentorship_requests')
    # ### end Alembic commands ###
