"""update notifications

Revision ID: cd245e8a9652
Revises: 62b87b534e86
Create Date: 2026-06-25 00:09:29.676189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd245e8a9652'
down_revision: Union[str, Sequence[str], None] = '62b87b534e86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('action_url', sa.String(), nullable=True))
    op.add_column('notifications', sa.Column('read_at', sa.DateTime(), nullable=True))
    op.add_column('notifications', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.alter_column('notifications', 'created_at', server_default=None)
    op.drop_column('notifications', 'read')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('read', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('notifications', 'created_at')
    op.drop_column('notifications', 'read_at')
    op.drop_column('notifications', 'action_url')
    # ### end Alembic commands ###
