"""add mentorship requests and sessions

Revision ID: fb7cf2fe1254
Revises: e19f2a3b4c5d
Create Date: 2026-06-30 22:55:02.405365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb7cf2fe1254'
down_revision: Union[str, Sequence[str], None] = 'e19f2a3b4c5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alumni_payouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alumni_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('session_count', sa.Integer(), nullable=False),
    sa.Column('payout_status', sa.String(), nullable=False),
    sa.Column('payment_method', sa.String(), nullable=True),
    sa.Column('transaction_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['alumni_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alumni_payouts_id'), 'alumni_payouts', ['id'], unique=False)
    op.create_table('alumni_earnings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alumni_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('student_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['alumni_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['mentorship_sessions.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alumni_earnings_id'), 'alumni_earnings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alumni_earnings_id'), table_name='alumni_earnings')
    op.drop_table('alumni_earnings')
    op.drop_index(op.f('ix_alumni_payouts_id'), table_name='alumni_payouts')
    op.drop_table('alumni_payouts')
    # ### end Alembic commands ###
